// Shared dropdown options for minister forms.
// Generated from Churches By Associations.xlsx (sheet: Churches by Association).

export const SECTOR_ASSOCIATION_MAP: Record<string, string[]> = {
  "Mid-Ghana Sector": [
    "Adansi Baptist Association",
    "Adom Baptist Association",
    "Bethel Baptist Association",
    "Golden Gate Baptist Association",
    "Kumasi North Baptist Association",
    "Kumasi South-East Baptist Association",
    "Kumasi South-West Baptist Association",
    "Kumasi West Baptist Association",
    "Sunyani Baptist Association"
  ],
  "Northern Ghana Sector": [
    "Bolga Baptist Association",
    "Liberty Baptist Association",
    "Nakpanduri Baptist Association",
    "Nalerigu Baptist Association",
    "North Eastern Baptist Association",
    "Tahima Baptist Association",
    "Tamale Baptist Association",
    "Wa Baptist Association"
  ],
  "South-East Ghana Sector": [
    "Accra North Baptist Association",
    "Accra South Baptist Association",
    "Dangbe West Baptist Association",
    "Dangme East Baptist Association",
    "Eastern Baptist Association",
    "North Volta Baptist Association",
    "South Volta Baptist Association",
    "Tema Central Baptist Association"
  ],
  "South-West Ghana Sector": [
    "Cape Coast Baptist Association",
    "Hope Baptist Association",
    "Nzema Baptist Association",
    "Sekondi-Takoradi Baptist Association",
    "Swedru Baptist Association",
    "Winneba Baptist Association"
  ]
};

export const ASSOCIATION_CHURCH_MAP: Record<string, string[]> = {
  "Adansi Baptist Association": [
    "Adom Baptist Church, Sansu – Adansi",
    "Agape Baptist Church, Kobro – Amansi",
    "Amazing Grace Baptist Church, Sunhyenso - Amansi",
    "Anointing Baptist Church, Apitiso",
    "Calvary Baptist Church, Anyinam - Obuasi",
    "Central Baptist Church, New Nyamebekyere - Obuasi",
    "Divine Baptist Church, Fumso - Adansi",
    "Emmanuel Baptist Church, Anhwiaso - Adansi",
    "Evangelical Baptist Church, New Edubiase",
    "Faith Evangelical Baptist Church, New Nyamebekyere",
    "First Baptist Church, Adinkra - Obuasi",
    "First Baptist Church, Old Estate - Obuasi",
    "God’s Love Baptist Church, Brofoyedu",
    "Gospel of Peace Baptist Church, Praso - Adansi",
    "Grace Baptist Church, Asokwa – Adansi",
    "Grace Outreach Baptist Church, Nyameso - Obuasi",
    "Joy Baptist Church, Kwabenakwa - Obuasi",
    "Joyful Way Baptist Church, Kunka Junction – Obuasi",
    "Living Word Baptist Church, Akrokerri - Adansi",
    "New Life Baptist Church, Homase - Amansi",
    "Precious Action Baptist Church, Kwapia Adansi",
    "Redemption Baptist Church, Bogobri – Obuasi",
    "Resurrection Power Baptist Church, Dompoase - Adansi",
    "Revival Baptist Church, Asanso",
    "Revival Baptist Church, Bekwai - Amansie",
    "Salvation Baptist Church, Akrofuom - Adansi",
    "Shalom Baptist Temple, Boete",
    "Shalom Baptist Temple, Kwabrafoso – Obuasi",
    "Solid Rock Baptist Church, Nteben – Amansie Central",
    "St. John’s Baptist Church, Brahabbome – Obuasi",
    "The Gate Baptist Church, Jacobu - Amansi",
    "The Light Baptist Church",
    "Triumphant Baptist Church, Akaporiso - Obuasi",
    "Triumphant Baptist Church, Asonkore",
    "Unity Baptist Church, Hia"
  ],
  "Adom Baptist Association": [
    "Acts Baptist Church, Tadieso / Bomini - Techiman",
    "Adom Baptist Church, Techiman",
    "Adom Baptist Church, Techiman-Kenten",
    "Christ the King Baptist Church, Busunya",
    "Disciples' Baptist Church, Wenchi",
    "Emmanuel Baptist Church, Akuropong",
    "Emmanuel Baptist Church, Asantanso",
    "Faith Baptist Church, Tanoso Addaekrom",
    "Faith Baptist Church, Techiman",
    "Family of God Baptist Church, Forikrom",
    "Fountain of Grace Baptist Church, Nkwaeso-Techiman",
    "Glory Baptist Church, Techiman",
    "Gospel Baptist Church, Adutwie",
    "Grace Baptist Church, Akumadan-Ashanti",
    "Holy Baptist Church, Traa Techiman",
    "Holy Ghost Baptist Church, Awisa-Wenchi",
    "Holy Ghost Baptist Church, Techiman",
    "Hope Baptist Church, Bonsu-Nkoranza",
    "Living Baptist Church, Kuntunso-Techiman",
    "Mount Zion Baptist Church, Tuobodom",
    "New Life Baptist Church, Nkoranza",
    "Nkunim Baptist Church, Techiman",
    "Peace Baptist Church, Wenchi Nchiraa",
    "Prince of Peace Baptist Church, Jema",
    "Resurrection Power Baptist Church, Abourso -Techiman",
    "Salvation Baptist Church, Akumadan-Afrancho",
    "Salvation Baptist Church, Kintampo-Tafo",
    "Temple of Fire Baptist Church, Babatokuma",
    "Temple of Fire Baptist Church, Kintampo",
    "Temple of Fire Baptist Church, Kyeremankuma",
    "Temple of Fire Baptist Church, Nante",
    "Temple of Revival Baptist Church, Amoma",
    "The Gospel Baptist Church, Techiman",
    "Trinity Baptist Church, Chirehin",
    "Victory Life Baptist Church, Aworowa",
    "Winners Community Baptist Church, Wenchi"
  ],
  "Bethel Baptist Association": [
    "Agape Baptist Church, Sefwi Bekwai",
    "Alive Baptist Church, Ahyiresu",
    "Anidaso Baptist Church, Chriano",
    "Bethel Baptist Church, Juaboso",
    "Calvary Baptist Church, Humjibre",
    "Christ the King Baptist Church, Essase",
    "Ebenezer Baptist Church, Sefwi Bekwai",
    "Emmanuel Baptist Church, Dansokrom",
    "Faith – Way Baptist Church, Egyakaa - Manso",
    "Faith Alive Baptist Church, Baakokrom",
    "Fountain of Life Baptist Church, Debiso",
    "Freedom Baptist Church, Antwiagyeikrom",
    "Gospel Baptist Church, Dwinase",
    "Grace Baptist Church, Asafo",
    "Grace Baptist Church, Ayiem",
    "Heaven’s Gate Baptist Church, Akomtonmera",
    "Heaven’s Gate Baptist Church, Ampenkrom",
    "Liberty Baptist Church, Fosukrom",
    "Living Faith Baptist Church, Ahwiaso",
    "Living Hope Baptist Church, Wiawso",
    "Living Waters Baptist Church, Dadieso",
    "Miracle Baptist Church, Diaso",
    "Mount Zion Baptist Church, Samfifre",
    "Mt. Zion Baptist Church, Kama",
    "New Life Baptist Church, Tanoso",
    "Patience Baptist Church, Wenchi",
    "Peace Baptist Church, Kwakuboa",
    "Prince of Peace Baptist Church, Bodi",
    "Proso Baptist Church, Proso",
    "Redemption Baptist Church, Kunkumso",
    "Revival Baptist Church, Afare",
    "Royal Baptist Church, Bibiani Old Town",
    "Royal Baptist Church, Hwenampori",
    "Royal Baptist Church, Nyinahin",
    "Royal Central Baptist Church, Bibiani",
    "St. James Baptist Church, Muoho",
    "St. Johns Baptist Church, Asawinso 'a'",
    "Unity Baptist Church, Bosomboso",
    "Unity Baptist Church, Wiawso",
    "Victory Baptist Church, Awaso"
  ],
  "Golden Gate Baptist Association": [
    "Adwumakasekese Baptist Church",
    "Anointing Baptist Church, Atimatim New Site",
    "Ash Town Baptist Church",
    "Berea Baptist Church, Mampong-daaho",
    "Bethel Baptist Church, Agona",
    "Central Baptist Church, Manhyia Extension",
    "Christ Baptist Church, Pankrono",
    "Divine Baptist Church, Bomfa",
    "Divine Hand Baptist Church, Pankrono",
    "El-shaddai Baptist Church, Bampenase",
    "Eternal Life Baptist Church, Mampong",
    "Eternal Life Baptist Church, Moshie Zongo",
    "Faith Community Baptist Church, Aduamoah",
    "Faith Community Baptist Church, Adubinsu",
    "Faith Community Baptist Church, Atimatim",
    "Faith Community Baptist Church, Essen Atimatim",
    "Faith Community Baptist Church, Tabuo",
    "First Baptist Church, Yeji",
    "Global Deliverance Baptist Church, Tafo Nhyiaeso",
    "Glory Baptist Church, Ejuratia",
    "Glory Baptist Church, Wiamoase",
    "Gospel Baptist Church, Abrewano",
    "Gospel Baptist Church, Ajamasu",
    "Gospel Baptist Church, Bonyo",
    "Gospel Baptist Church, Dome",
    "Gospel Baptist Church, Ejura",
    "Gospel Baptist Church, Sarikyi",
    "Gospel Light Baptist Church, Jamase",
    "Gospel Vessel Baptist Church, Moshie Zongo",
    "Grace Baptist Church, Atebubu",
    "Kingdom Baptist Church, Kofiase",
    "Kingsway Baptist Church, Buokrom",
    "Living Gospel Baptist Church, Kona",
    "Living Gospel Baptist Church, Mamponteng",
    "Living Gospel Baptist Church, Ntonso",
    "Living Waters Baptist Church, Meduma",
    "Maranatha Baptist Church, Kwamang",
    "Messiah Baptist Church, Mampong",
    "New Creation Baptist Church, Asonomaso",
    "New Creation Baptist Church, Fawoade",
    "New Life Baptist Church",
    "New Life Baptist Church, Dumanafo",
    "New Life Baptist Church, Kajaji",
    "Paradise Baptist Church, Maase",
    "Peniel Baptist Church, Mampong",
    "Prayer & Praise Baptist Church, Maase",
    "Pure Word Baptist Church, Meduma South",
    "Reach Out Baptist Church, Ahwiaa",
    "Repentance Baptist Church, Sekyeredumase",
    "Revival Baptist Church, Kwame Danso",
    "Salvation Gate Baptist Church, Mamponteng Achiase",
    "Shalom Baptist Church, Adwumam",
    "Solid Rock Baptist Church, Tafo Adompom",
    "Victory Baptist Church, Nsuta",
    "Vineyard Baptist Church, Pankrono Estate",
    "Zoe Baptist Church, Beposo"
  ],
  "Kumasi North Baptist Association": [
    "Adom Baptist Church, Koforidua",
    "Agape Baptist Church, Ahenkuro",
    "All Souls Baptist Church, Adoato",
    "Anointing Baptist Church, Besease",
    "Apagya Baptist Church",
    "Asomdwoe Baptist Church, Asonomaso",
    "Asomdwoe Baptist Church, Mfensi",
    "Believers Baptist Temple",
    "Believers Baptist Temple (All Believers), Serebouso",
    "Believers Baptist Temple (Eternal Life), Bedefi",
    "Believers Baptist Temple (Perfect Glory), Anyinamso No. 2",
    "Believers Baptist Temple (Resurrection), Bedaabour",
    "Believers Baptist Temple (Soul Winners), Beposo",
    "Berea Baptist Church, Breman UGC",
    "Bethel Baptist Church, Sabronum",
    "Blessing Baptist Church, Dabaan",
    "Bread of Life Baptist Church, Bronkong, Kronum Kwapra",
    "Charity Baptist Church, Offinso",
    "Emmanuel Baptist Church, Anomangye",
    "Emmanuel Baptist Church, Sasa",
    "Eternal Life Baptist Church, Abufour",
    "Eternal Life Baptist Church, Barekese",
    "Eternal Life Baptist Church, Nkwaakwaa",
    "Eternal Life Baptist Church, Offinso",
    "Eternity Life Baptist Church, Ahenkuro",
    "Evangelical Baptist Church, Suame",
    "Faith Arena Baptist Church",
    "First Baptist Church, Boamang",
    "Glory Baptist Church, Adiembra",
    "Glory Baptist Church, Sepaase",
    "Glory El Baptist Church",
    "God Is King Baptist Church, Namong, Wenchi",
    "God's Favor Baptist Church, Kronum Kyerase",
    "God’s Love Baptist Church, Mpatase",
    "Good News Baptist Church, Offinso",
    "Gospel Baptist Church",
    "Holy Family Baptist Church, Afrancho",
    "Hope Baptist Church, Abroma",
    "House of Prayer Baptist Church, Ohwim",
    "Jubilee Baptist Church",
    "King of Kings Baptist Church",
    "Kingdom Life Baptist Church",
    "Lifeway Baptist Church, Nyankyerenease",
    "Living Faith Baptist Church, Anomangye",
    "Living God Baptist Church, Offinso",
    "Living Word Baptist Church, Danase",
    "Love Baptist Church",
    "Love Baptist Church, Esaase",
    "Maranatha Baptist Church, Kronum",
    "Mercy Baptist Church, Tetrem",
    "Multi Ethnic Baptist Church, Abuakwa",
    "New Era Baptist Church, Mankranso",
    "New Hope Baptist Church, K. Dwaa",
    "New Life Baptist Church, Barekese",
    "New Life Baptist Church, Mpasatia",
    "Nhyira Baptist Church, Abofour",
    "Nhyira Baptist Church, Ahwerewam",
    "Oasis of Peace Baptist Church, Ohwim",
    "Prince of Peace Baptist Church",
    "Prince of Peace Baptist Church, Asuofia",
    "Redeem Baptist Church",
    "Redeemer Baptist Church, Kodie",
    "Rescue Baptist Church, Adoato",
    "Rhema Baptist Church, Kronum Kwapra",
    "Rhema Baptist Church, Kwapanin",
    "Royal Life Baptist Church",
    "Salvation Baptist Church, Kwamang",
    "Salvation Baptist Church, Namong",
    "St Anthony Baptist Church",
    "St James Baptist Church, Bantama",
    "St John Baptist Church, Bremang West",
    "St. James Baptist Church",
    "The Living Word Baptist Church, Bremang Nkwantwima",
    "Triumphant Baptist Church",
    "Triumphant Baptist Church, Apatrapa",
    "Truth Way Baptist Church, Achiase",
    "Unity Baptist Church, Akropong",
    "Victory Baptist Church, Offinso Old Town"
  ],
  "Kumasi South-East Baptist Association": [
    "Antioch Baptist Church, Kumasi",
    "Ascension Baptist Church, Effiduase",
    "Bepong Baptist Church",
    "Bethel Baptist Church, Airport Roundabout",
    "Bethel Baptist Church, Truba",
    "Bethesda Baptist Church, Adadientem",
    "Bethesda Baptist Church, Asamang",
    "Bethesda Baptist Church, Ejisu",
    "Bethesda Baptist Church, Krapa",
    "Calvary Baptist Church, Abetifi",
    "Calvary Baptist Church, Ejisu Manhyia",
    "Christian Baptist Church, Juaben",
    "Divine Baptist Church, Sawaba",
    "Divine Grace Baptist Church, Effiduase",
    "Faith Baptist Church, Asotwe",
    "First Baptist Church, Akwatia-line",
    "Flames of Love Baptist Church, Nkawkaw",
    "Fountain of Life Baptist Church, Nsenie",
    "Full Gospel Baptist Church",
    "Full Life Baptist Church, Parkoso",
    "Glory Baptist Church, Adukrom",
    "Glory Baptist Church, Effiduase",
    "God’s Family Baptist Church, Akyease",
    "Good News Baptist Church, Nkawkaw",
    "Goshen Baptist Church, Ahwerewa",
    "Gospel Baptist Church, Abirem",
    "Gospel Baptist Church, Bosore",
    "Grace Baptist Church, Adako Jachie",
    "Grace Baptist Church, Amakom",
    "Grace Baptist Church, Ejisu Jamasi",
    "Holy Spirit Baptist Church, Patrensa",
    "House of Grace Baptist Church",
    "Lifeway Baptist Church, Asakraka",
    "Living Fountain Baptist Church, Asokore",
    "Living Hope Baptist Church, Oduom",
    "Living Word Baptist Church, Dote",
    "Macedonia Baptist Church, Akokoamon",
    "Messiah Baptist Church, Tikrom",
    "Miracle Baptist Church, Kumawu",
    "Mt. Zion Baptist Church, Effiduase",
    "New Life Baptist Church, Adanwomase",
    "New Life Baptist Church, Senchi",
    "Obo Baptist Church, Kwahu",
    "Omega Baptist Church, Bonwire",
    "Open Door Baptist Church, Kentinkrono",
    "Peace Baptist Church, Agogo",
    "Pentecostal Baptist Church, Akyawkrom",
    "Prince of Peace Baptist Church, Antoa",
    "Resurrection Baptist Church, Okyerekrom",
    "Revival Baptist Church, Oyoko",
    "Royal Baptist Church, Kenyase",
    "Salvation Baptist Church, Agogo",
    "Salvation Baptist Church, Akoasi",
    "Second Coming Baptist Church, Sepe-timpon",
    "Solid Rock Baptist Church, Aprade",
    "Soul Winners Baptist Church, Dadiese",
    "St. Albert Baptist Church, Ejisu",
    "Suhudoo Baptist Church, Kumasi",
    "Temple of Praise Baptist Church, Low-cost",
    "Unity Baptist Church, Asokore-effiduase",
    "Victory Baptist Church, Abira",
    "Victory Baptist Church, Ayigya",
    "Victory Baptist Church, Ntomim"
  ],
  "Kumasi South-West Baptist Association": [
    "Acts Baptist Church, Hwereso",
    "Acts Charismatic Baptist Church, Kwamo",
    "Ahinsan Baptist Church, Ahinsan",
    "Ascension (Frafra) Baptist Church, Bomso",
    "Ascension (Frafra) Baptist Church, Kotei",
    "Ascension Baptist Church, Appiadu",
    "Ascension Baptist Church, Bomso",
    "Ascension Baptist Church, Dompoase Aprabo",
    "Ascension Baptist Church, Ejisu Asawasi",
    "Aseda Baptist Church, Adagya",
    "Asokwa Baptist Church",
    "Berea Baptist Church, Dompoase",
    "Bible Way Baptist Church, Boadi",
    "BIWC Baptist Church, Asokwa",
    "Blessing Baptist Church, Deduako",
    "Born Again Baptist Church, Onwe",
    "Broken Yoke Baptist Church, Abuontem",
    "Central Charismatic Baptist Church, Gyinyase",
    "Disciples Baptist Church, Ejisu-abenase",
    "Divine Baptist Church, Adwampong",
    "Divine Baptist Church, Apromase",
    "Divine Baptist Church, New Kokobireko",
    "Divine Zion Baptist Church, Emena Boadi",
    "Dominion Baptist Church, Yaase",
    "Donewell Baptist Church, Donyina",
    "Ebenezer Baptist Church, Amangoase",
    "El-shaddai Baptist Church, Ahinsan Estate",
    "Emmanuel Baptist Church, Adwumam",
    "Eternal Life Baptist Church, Ahinsan",
    "Evangelical Baptist Church, Domeabra",
    "Faith Baptist Church, Abidjan-nkwanta",
    "Faith Baptist Church, Nkwanta",
    "Family Baptist Church, Anwomaso",
    "Feyiase Baptist Church, Feyiase",
    "Friendship Baptist Church, Besease",
    "Gate Way Baptist Church, Dompoase",
    "Glory Temple Baptist Church, Ampabame",
    "Grace Baptist Church, Asaman",
    "Grace Baptist Church, Appiadu-Kokoben",
    "Grace Baptist Church, Foase Kokoben",
    "Grace Baptist Church, Obogu",
    "Harvest Baptist Church, Jachie",
    "Harvestime Baptist Church, Atonsu",
    "Heaven Gate Baptist Church, Domee",
    "Holy Life Baptist Church, Akokofe",
    "Holy Temple Baptist Church, Chirapatre",
    "Kingdom Baptist Church, Sewua",
    "Lakeroad Baptist Church, Kuntenase",
    "Liberty Baptist Church, Konongo",
    "Lighthouse Baptist Church, Ayeduase",
    "Living Faith Baptist Church, Boama Dumase",
    "Love Baptist Church, Daban Payin",
    "Mercy Baptist Church, Anloga",
    "Mt. Olivet Baptist Church, Ahodwo",
    "New Life Baptist Church, New Koforidua",
    "New Life Baptist Church, Praaso",
    "New Life Baptist Church, Deduako",
    "New Life Baptist Church, Oyoko",
    "Peace Baptist Church, Essienimpong",
    "Praise Baptist Church, Atonsu S-line",
    "Praise Baptist Church, Aputuogya",
    "Redemption Baptist Church, Atonsu Kuwait",
    "Renewed Life Baptist Church, Esreso",
    "Revival Baptist Church, Asante Akyem Bompata",
    "Rhema Baptist Church High Tension",
    "Rhema Baptist Church, Kokofu",
    "Saviour Baptist Church, Fumesua",
    "Seekers Baptist Church, Aduaben",
    "Truth Baptist Church, Konongo-odumase",
    "Unity Baptist Church Juaso",
    "Upper Room Baptist Church, Oti - Kumasi",
    "Victory Baptist Church, Achinakrom",
    "Vision Baptist Church, Pramso",
    "Winners Baptist Church, Kwaso",
    "Zion Baptist Church, Kotei"
  ],
  "Kumasi West Baptist Association": [
    "Adom Baptist Church, Atwima Behenase",
    "Alpha & Omega Baptist Church, Kaniago",
    "Amazing Grace Baptist Church, Aboabokese",
    "Ascension Baptist Church, Trede",
    "Aseda Baptist Church, Mem",
    "Believers Baptist Church, Takorasi",
    "Calvary Baptist Church, Nkran",
    "Calvary Baptist Church, Nzema",
    "Christ Indwelling Baptist Church, Mim",
    "Christ the King Baptist Church, Hiakose",
    "Christ the King Baptist Church, Suntreso",
    "Confidence Baptist Church, Manso Yawkrom",
    "Disciples Baptist Church, Ampatia",
    "Divine Baptist Church, Anyinam",
    "Dr. Verner Baptist Church, Kumpese",
    "Ebenezer Baptist Church, Denkyemuoso",
    "Ebenezer Baptist Church, Kwadaso Owhimase",
    "Ebenezer Baptist Church, Mmorho",
    "Eden Baptist Church, Kwankyeabo",
    "Emmanuel Baptist Church, Abakomadi",
    "Eternal Life Baptist Church, Datano",
    "Faith Baptist Church, Antoakrom",
    "Fountain Gate Baptist Church, Bebu",
    "Fountain Gate Baptist Church, Pakyi",
    "Freedom Baptist Church, Foase",
    "Gateway Baptist Church, Maakro",
    "Gateway Baptist Church, Nerebehi",
    "Glory Baptist Church, Abore",
    "Goodness Baptist Church, Brofeyedru",
    "Goodness Baptist Church, Brofoyedru",
    "Gospel Baptist Church, Moseaso",
    "Grace Baptist Church, Nwineso 2",
    "Grace Baptist Church, Foase Kokoben",
    "Grace Baptist Church, Kobriso",
    "Grace Baptist Church, Santasi",
    "Greater Love Baptist Church, Manso Agroyesum",
    "Harvesters Baptist Church, Twedie",
    "Heaven Seat Baptist Church, Kwabenaso",
    "Heaven's Gate Baptist Church, Akwasiso",
    "Hope Baptist Church, Manso Atwere",
    "Joy Baptist Church, Fankyenebra",
    "Joy Baptist Church, Kotwi",
    "Kingsway Baptist Church, Nipa Nkyeremia",
    "Liberty Baptist Church, Afrancho",
    "Lighthouse Baptist Church, TUC",
    "Living Baptist Church, Stoneaborso",
    "Living Bible Baptist Church, Edwenase",
    "Living Spring Baptist Church, Atwima Boko",
    "Living Word Baptist Church, Kromoase Newsite",
    "Livingspring Baptist Church, Atasemanso",
    "Livingsprings Baptist Church, Poano",
    "Love Baptist Church, Manso Odaho",
    "New Hope Baptist Church, Kokoben",
    "New Life Baptist Church, Adubia",
    "Nhyira Baptist Church, Essowin",
    "Nkunim Baptist Church, Manso Nkwanta",
    "Nkunim Baptist Church, Nkawie",
    "Nkunim Baptist Church, Nkwakom Near Nkawie",
    "Peace & Love Baptist Church, Dawusaso",
    "Peace Baptist Church, Daban",
    "Peace Baptist Church, Watreso",
    "Providence Baptist Church, Abuakwa",
    "Reapers Baptist Church, Dida",
    "Redemption Baptist Church, Fahiakobo",
    "Rescue Hour Baptist Church, Apire",
    "Restoration Baptist Church, Ahwerewa",
    "Revelation Baptist Church, Abiram",
    "Revival Baptist Church, Anwiankwanta",
    "Rhema Baptist Church, Nwineso 1",
    "Royal Community Baptist Church, Atwima Agogo",
    "Royals Baptist Church, Gyeduako",
    "Salvation Baptist Church, Ayiem",
    "Salvation Baptist Church, Manso Afidea",
    "Salvation Baptist Church, Trabuon",
    "Savior Baptist Church, Amanchia",
    "Shalom Baptist Church, Manso Suntreso",
    "The Word Baptist Church, Tanoso",
    "Trinity Baptist Church, Adjamesu",
    "Trinity Baptist Church, Apaase",
    "Trinity Baptist Church, Dominase",
    "Trinity Baptist Church, Patasi",
    "Triumphant Baptist Church, Kwadaso",
    "Triumphant Baptist Church, Toase",
    "Victory Baptist Church, Essienkyem",
    "Victory Baptist Church, Koben",
    "Victory Baptist Church, Tontokrom",
    "Victory Baptist Church, Trede",
    "Winners Baptist Church, Nkorang"
  ],
  "Sunyani Baptist Association": [
    "Abundant Life Baptist Church, Goaso",
    "Action Charismatic Baptist Church, Kwameseikrom",
    "Anointing Baptist Church Churc, Saketia",
    "Anointing Baptist Church, Asiri",
    "Anointing Baptist Church, Duadaso 2",
    "Anointing Baptist Church, Gonasua",
    "Asempa Baptist Church, Dodosuo",
    "Baptist Church International Worship Centre, Sunyani",
    "Bethel Baptist Church, Old Drobo",
    "Bethel Charismatic Baptist Church, Tepa",
    "Blessed Baptist Church Jinijini, Bono West",
    "Botokrom Baptist Church, Botokrom",
    "Calvary Baptist Church, Kotokrom",
    "Calvary Baptist Church, Sunyani New Town",
    "Diciples Baptist Church, Faaman",
    "Ebenezer Baptist Church, Japekrom",
    "Ebenezer Baptist Church, Nkyemnkyemanu",
    "Emmanuel Baptist Church, Babiniha",
    "Faith Baptist Church Wuramso",
    "Faith Baptist Church, Buobumu",
    "Family Baptist Church, Asare-mempeasem",
    "Family of God Baptist Church, Dormaa Ahenkro",
    "Family of God Baptist Church, Wamfie",
    "First Baptist Church, Adiokor",
    "Glorious Baptist Church",
    "Glorious Baptist Church, Baakoniaba",
    "Glorious Baptist Church, Miramano",
    "Grace Baptist Church, Beaso",
    "Grace Baptist Church, Berekum",
    "Grace Baptist Church, Kasapee",
    "Grace Baptist Church, Mim",
    "Heaven Gate Baptist Church, Mpuasu",
    "Hope Baptist Church Nkasaem",
    "JJMJ Aseda Baptist Church",
    "Joy Baptist Church Ntotroso",
    "Joy Baptist Church, Kofiko",
    "Jubilee Baptist Church, Kukuom",
    "Kingsway Family Baptist Church, Drobo, Jaman South",
    "Life Baptist Church, Hwidiem",
    "Love Baptist Church, Amanfrom",
    "Love Community Baptist Church, Nsoatre",
    "Mercy Baptist Church, Nkwabeng North, Sunyani",
    "Miracle Baptist Church, Dwenem, Jaman South",
    "Mount Zion Baptist Church, Chiraa",
    "New Life Baptist Church, Abesim-sunyani",
    "Peace Baptist Church, Mmehame",
    "Power Baptist Church, Ahafo Kenyasi",
    "Precious Baptist Church, Asuogya",
    "Prince of Peace Baptist Church, Bomaa",
    "Resurrection Baptist Church, Brosankro Tepa",
    "Rhema Baptist Church, Yamfu",
    "Salvation Baptist Church, Abirakasu",
    "Salvation Baptist Church, Akyerensua",
    "Salvation Baptist Church, Fiapre - Sunyani",
    "Salvation Baptist Church, Suma Ahenekro",
    "Shalom Baptist Church, Katakyiekrom",
    "The Good Shepherd Baptist Church, Subonpang",
    "Unity Baptist Church Adamsu",
    "Unity Baptist Church, Atuna",
    "Victorious Baptist Church, Sunyani Odomase",
    "Victory Baptist Church, Bechem",
    "Victory Baptist Church, Drobo, Jaman South",
    "Zion Baptist Church, Sampa"
  ],
  "Bolga Baptist Association": [
    "Atuba Baptist Church",
    "Bawku ( Central Baptist Church)",
    "Beo Baptist Church, Kanzingo",
    "Calvary Baptist Church",
    "Ebenezer Baptist Church, Bawku",
    "Emmanuel Baptist Church ( Narvongo)",
    "Faith Baptist Church",
    "First Baptist Church",
    "Gane-asonge Baptist Church",
    "God's Glory Baptist Church, Zaare",
    "Greenland Baptist Church, Tongo",
    "Harvest Baptist Church",
    "Kancingo Baptist Church",
    "King of Kings Baptist Church, Narvongo",
    "Kuolimasigu Baptist Church",
    "Liberty Baptist Church",
    "Livingstone Baptist Church",
    "Messiah Baptist Church, Bongo",
    "Milk and Honey Baptist Church",
    "Mt Zion Baptist Church",
    "New Hope Baptist Church",
    "Redeem Baptist Church",
    "Redemption Baptist Church, Sandema",
    "Redemption Baptist Church, Zorko",
    "Resurrection Baptist Church",
    "Solid Rock Baptist Church",
    "St-Leo Baptist Church",
    "Victory Baptist Church",
    "Wiaga Baptist Church, Guuta",
    "Zaare Baptist Church",
    "Zuarungu Baptist Church"
  ],
  "Liberty Baptist Association": [
    "Daboya Baptist Church",
    "Dissah Baptist Church",
    "Ebenezer Baptist Church",
    "Gbasimpa Baptist Church",
    "Jerusalem Baptist Church",
    "Liberty Baptist Church",
    "Nabengu Baptist Church",
    "Redeem Baptist Church",
    "Salugu Baptist Church",
    "Singa Baptist Church",
    "Tari No.1 Baptist Church",
    "Tari No.2 Baptist Church",
    "Tenbang Baptist Church",
    "Triumph Baptist Church",
    "Tunsugu Baptist Church",
    "Victory Baptist Church"
  ],
  "Nakpanduri Baptist Association": [
    "Bunkpurugu Baptist Church",
    "Corner Stone Baptist Church",
    "Dennugu Baptist Church",
    "El- Shadai Baptist Church",
    "Jagoak Baptist Church",
    "Kpatrintiga Baptist Church",
    "All For God Baptist Church, Kukparigbini",
    "Miracle Baptist Church - Namenboku",
    "Nabuik Baptist Church",
    "Nakpabon Baptist Church",
    "Nakpanduri Baptist Church",
    "Nankpanbon Baptist Church",
    "Nanponitibuak Baptist Church",
    "Nyamiwai Baptist Church",
    "Restoration Baptist Church",
    "Holy Ghost Baptist Church, Sabona",
    "Sakogu Baptist Church",
    "Sakogu Baptist Church, Bombila",
    "Salvation Baptist Church",
    "Soansobigu Baptist Church",
    "Tartara Baptist Church",
    "Toumoni Baptist Church",
    "Unity Baptist Church"
  ],
  "Nalerigu Baptist Association": [
    "Badinduguru Baptist Church",
    "Banjam Baptist Church",
    "Bethel Baptist Church",
    "Boatrigu Baptist Church",
    "Boayini Baptist Church",
    "Bongbini Baptist Church",
    "Bongni Baptist Church",
    "Bonnie Baptist Church",
    "Bowku Baptist Church",
    "Bumboazio Baptist Church",
    "Burugu Baptist Church",
    "Central Baptist Church - Walewale",
    "Cornerstone Baptist Church",
    "Dagberiboari Baptist Church",
    "Dintigi Baptist Church",
    "Emmanuel Baptist Church",
    "First Baptist Church - Nalerigu",
    "Fulbe Baptist Church",
    "Gaabini Baptist Church",
    "Gabonna Baptist Church",
    "Gabonni Baptist Church",
    "Gbangu Baptist Church",
    "Gbingbiriga Baptist Church",
    "Gbintri Baptist Church",
    "Gokabulga Baptist Church",
    "Good Shepherd Baptist Church",
    "Guabuliga Baptist Church",
    "Hope Charismatic Baptist Church",
    "Kolinvai Baptist Church",
    "Konni Baptist Church",
    "Kpabigu Baptist Church",
    "Kulgona Baptist Church",
    "La-atarigu Baptist Church",
    "Langbina Baptist Church",
    "First Baptist Church, Langbinsi",
    "Second Baptist Church, Langbinsi",
    "Nagboo Baptist Church",
    "Namangu No.1 Baptist Church",
    "Namarigu Baptist Church",
    "Namniyala Baptist Church",
    "Nasuan Baptist Church",
    "Sakobunbong Baptist Church",
    "Sammni Baptist Church",
    "Soasoeigi Baptist Church",
    "Suanvusi Baptist Church",
    "Sumniboma Baptist Church",
    "Sumniboma No 2 Baptist Church",
    "Tangbini Baptist Church",
    "Timpela Baptist Church",
    "Trinity Baptist Church",
    "Victory Baptist Church",
    "Walewale Central Baptist Church",
    "Wundua Baptist Church, Langbinsi",
    "Yaama Baptist Church",
    "Yunyodani Baptist Church",
    "Yunyoranyiri Baptist Church",
    "Za-anoriyoya Baptist Church",
    "Zaadantinga Baptist Church",
    "Zaari Baptist Church",
    "Zagri Baptist Church",
    "Zambulgu Baptist Church",
    "Zambulugu Baptist Church",
    "Zandua Baptist Church",
    "Zanoriyuaya Baptist Church",
    "Zarantinga Baptist Church",
    "Zikaya Baptist Church",
    "Zogiligu Baptist Church"
  ],
  "North Eastern Baptist Association": [
    "Abundant Grace Baptist Church Lanjah",
    "Anthioch Baptist Church, Bandiyili",
    "Arising Baptist Church Ojojah",
    "Attado Baptist Church",
    "Bachado Baptist Church Bachado",
    "Baduli Passover Baptist Church, Baduli",
    "Savior Baptist Church, Bagmark",
    "Bakpaba Baptist Churchbakpaba",
    "Believer Baptist Church, Namani",
    "Belindo Baptist Church, Belindo",
    "Benambador Baptist Church Benambador",
    "Benayili Baptist Church, Benayili",
    "Bethel Baptist Church, Nyojado",
    "Bethlehem Baptist Church, Konlado",
    "Bichado Grace Baptist Church Bichado",
    "Bignondo Baptist Church",
    "Bilmado Baptist Church Bilmado",
    "Bitido Baptist Church, Bitido",
    "Blessed Baptist Church Upando",
    "Blessed Baptist Church, Yalnke",
    "Blessing of God Baptist Church, Seburini",
    "Bofoyili Baptist Church Bofoyili",
    "Bogjoo Baptist Church Bogjoo",
    "Bogni Baptist Church Bogni",
    "Boiboni Baptist Church Boiboni",
    "Bolni No 3 Baptist Church Bolni",
    "Bolsildo Baptist Church Bolsildo",
    "Born Air Baptist Church, Kpandai",
    "Branch Baptist Church, Bawado",
    "Bula No2 Baptist Church Bula No2",
    "Bunbong Baptist Church Bunbong",
    "Bungbali Baptist Church Bungbali",
    "Calvary Baptist Church Sak-siik",
    "Chakorni Baptist Church, Chakorni",
    "Chakundor Baptist Churchchakundor",
    "Chakutido Baptist Church Chakutido",
    "Choo Baptist Church Choo",
    "Chopondo Baptist Church Chopondo",
    "Conner Stone Baptist Church, Zagbang",
    "Cross Over Baptist Church, Tinangeria",
    "Dabreeni Baptist Church Dabreeni",
    "Danador Baptist Church, Danador",
    "Davis Baptist Church, Waseni",
    "Deeni Baptist Church, Deeni",
    "Delivery Baptist Church, Nkanchina",
    "Dikpali Baptist Church Dikpali",
    "Dipah Baptist Church Dipah",
    "Discon Baptist Church, Litultab",
    "Ditney Baptist Church, Yendi",
    "Divine Baptist Church, Gmagmamtido",
    "Duuni Baptist Church Duuni",
    "Eagle Wings Baptist Church, Yakubupe",
    "Elizabeth Baptist Church Gbandi",
    "Ellen Baptist Church, Benyikondo",
    "Emmanuel Baptist Church Jonayili",
    "Emmanuel Baptist Church Majado",
    "Eternal Life Baptist Church Makondo",
    "Faith Baptist Church, Achrido",
    "Faith Baptist Church, Napajado",
    "Faith Baptist Church Opijua",
    "Faith Baptist Church, Mayedo",
    "Faithful Baptist Church Bawado",
    "Faithful Baptist Church, Nyorlani",
    "Faithful Servant Baptist Church, Nyolakani",
    "Freedom Baptist Church Gmagundo",
    "Freedom Baptist Church, Bincheratanga",
    "Freedom Baptist Church, N-nalong",
    "Freedom Baptist Church, Yashegu",
    "Gambuga Baptist Church Gambuga",
    "Glory Baptist Church, Bagjo",
    "Gmangundor Baptist Church Gmangundor",
    "Gmataedo Baptist Church",
    "Gnanyando Baptist Church, Gnaayando",
    "Living Stone Baptist Church, Gnaribon",
    "God’s Glory Baptist Church, Kpako",
    "God’s People Baptist Church, Ichigado",
    "Good Faith Baptist Church, Kpalisub",
    "Good Shepherd Baptist Church, Napurido",
    "Grace Baptist Church Sabal Tindang",
    "Grace Baptist Church, Binanbado",
    "Grace Baptist Church, Kanimo",
    "Grace Baptist Church, Kitoe Nkwanta",
    "Grace Baptist Church, Kokwado",
    "Grace Baptist Church, Nogmado",
    "Grace Baptist Church, Pakgmado",
    "Gracious Baptist Church, Jimani 1",
    "Great Love Baptist Church",
    "Guluyansi Baptist Church, Guluyansi",
    "Gurtanedo Baptist Church, Gurtanedo",
    "Harvest Baptist Church, Makango",
    "Heaven Gate Baptist Church Kpasaa",
    "Hecret Baptist Church Egambodo",
    "His Grace Baptist Church Sakpei",
    "Hope Baptist Church, Montanaya",
    "Hope Baptist Church, Osonodo",
    "Hope Well Baptist Church, Binchakiyado",
    "House of Prayer Baptist Church",
    "Ignite Baptist Church, Achirido",
    "Ignite Baptist Church, Naprudo",
    "Jackson Baptist Church, Nyakpala No. 1",
    "Jagando Repentance Baptist Church Jagando",
    "Jagoya Baptist Church Jagoya",
    "Jagrido Baptist Church",
    "Jagrido Baptist Church Jagrido",
    "Jaguudo Baptist Church Jaguudo",
    "Janboni Baptist Church Janboni",
    "Jankpador Baptist Church Jankpador",
    "Jesus Is Love Baptist Church, Payotido 2",
    "Jesus Way Baptist Church, Yapero",
    "Jili Baptist Church, Jili",
    "Joy and Praise Baptist Church, Kabonwule",
    "Kanbordo Baptist Church Kanbordo",
    "Kangarido Baptist Church, Kangarido",
    "Kanjakura Joyful Baptist Church Kanjokura",
    "Kassapue Baptist Church Kassapue",
    "Kayang Baptist Church Kayang",
    "Kimoteek Baptist Church",
    "Kingdom of Life Baptist Church, Jabundo",
    "Kobalm Mayedo Baptist Church, Kobalm",
    "Kolkolni Baptist Churchkolkolni",
    "Konkonjorni Baptist Church Konkonjorni",
    "Korani Baptist Church Korani",
    "Kpabudo Baptist Church Kpabudo",
    "Kpajotibdo Baptist Church, Kpajotibdo",
    "Kpakuldo Baptist Church Kpakaldo",
    "Kpalikigbene Baptist Church, Kpalikigbene",
    "Kpaluni Baptist Church, Kpaluni",
    "Kpasak Baptist Church Kpasak",
    "Strong Faith Baptist Church, Kpasanando",
    "Kpendo Baptist Church, Kpendo",
    "Kubagmado Baptist Church Kubagmado",
    "Kubal Baptist Church Kubal",
    "Kukpaligu Baptist Church, Kukpaligu",
    "Kulboni Baptist Church",
    "Kulkpeni Baptist Church Kulkpeni",
    "Kunkong Baptist Church Kunkong",
    "Kunkunjoni Baptist Church Kunkunjoni",
    "Kwayajabo Baptist Church, Kwayajabo",
    "Labrado Baptist Church Labrado",
    "Lahito Jubilee Baptist Church Lahito",
    "Langbani Baptist Church Langbani",
    "Lenpusi Baptist Church Lenpusi",
    "Liberty Baptist Church Banda",
    "Liberty Baptist Church, Edzuma",
    "Light of the World Church Baptist Church, Nagani",
    "Lighthouse Baptist Church",
    "Lijobilbu Baptist Church, Lijobilbu",
    "Likpalntab Baptist Church, Likpalntab",
    "Living Baptist Church, Sikpam",
    "Living Hope Baptist Church, Tisali",
    "Living Water Baptist Church, Niboado",
    "Living Water Baptist Church, Wandamdo",
    "Love Baptist Church, Okodo",
    "Lover Baptist Church, Osonodo",
    "Manyini Baptist Church Manyini",
    "Maranatha Baptist Church Chamba",
    "Meme Baptist Church Meme",
    "Mercy Baptist Church, Polarido",
    "Miracle Baptist Church, Telibe",
    "Moba Baptist Church, Moba",
    "Monchani Baptist Church Monchani",
    "Monjibdo Baptist Church",
    "Moomido Baptist Church, Moomido",
    "Mount Zion Baptist Church, Kinybedo",
    "Nabori Baptist Church Nabori",
    "Nadundo Baptist Church Nadundo",
    "Nagbanbu Baptist Church, Nagbanbu",
    "Nagbi Baptist Church Nagbi",
    "Nakpaa Gbeni Baptist Church Nakpaagbeni",
    "Nakpachei Baptist Church Nakpachei",
    "Nakpaldadul Baptist Church",
    "Nandanbia Baptist Church Nandanbia",
    "Nansah Baptist Church, Kparibado",
    "Narrow Door Baptist Church, Jiliman",
    "Nashegu Baptist Church Nashegu",
    "Nasuwani Baptist Church Nasuwani",
    "Natiga Baptist Church Natinga",
    "Natondo Baptist Church, Natondo",
    "Neboni Shining Baptist Church Neboni",
    "New Beginning Baptist Church, Wisundo",
    "New Generation Baptist Church, Pebila",
    "New Hope Baptist Church, Kachilendo",
    "New Hope Baptist Church, Nyankpani",
    "New Life Baptist Church, Monchani",
    "New Life Baptist Church, Sabujida",
    "New Life Community Baptist Church, Bogni",
    "New Light Baptist Church, Puanjido",
    "Nkpani Baptist Churchnkpani",
    "Nkuubdo Baptist Church Nkuubdo",
    "Nlalerdo Baptist Church, Nlalerdo",
    "Nnanjimdo Baptist Church, Nnanjimdo",
    "Ntesindo Baptist Church, Ntesindo",
    "Nyamayamani Baptist Church",
    "Nyambolgi Baptist Church",
    "Nyamenboa Baptist Church, Nyamenboa",
    "Nyankpala Baptist Church Nyankpala",
    "Nyojador Baptist Church Nyajador",
    "Nyopedo Baptist Church, Nyopedo",
    "Obabido Baptist Church, Obabido",
    "Obondo Baptist Church Obondo",
    "Ogando Baptist Church Ogando",
    "Ogbenjah Baptist Church Ogbenjah",
    "Ojojah Baptist Church Ojojah",
    "Okodo Baptist Church, Okodo",
    "Omega Baptist Church, Wapuli",
    "Omoaldor Baptist Church Omoaldor",
    "Open Door Baptist Church, Buya",
    "Orchard Grove Baptist Church, Nasho 2",
    "Osaido Baptist Church Osaido",
    "Oyomdo Baptist Churchoyomdo",
    "Peace Baptist Church Yakal",
    "Peace Baptist Church, Kolikolini",
    "Peace Baptist Church, Kpassani",
    "Peace Baptist Church, Monchuni",
    "Peace Baptist Church, Nakpangii",
    "Peace Baptist Church, Nbulador",
    "Peace Baptist Church, Tasundo",
    "Peace Baptist Church, Zabzugu",
    "Pechedo Baptist Church, Pechedo",
    "Pemanbalni Baptist Church, Pemanbalni",
    "Pewundo Baptist Church, Pewundo",
    "Place of Grace Baptist Church, Kunbuni",
    "Provident Baptist Church, Salaga",
    "Redemption Baptist Church, Bubom",
    "Restoration Baptist Church, Gnani Tandem",
    "Resurrection Baptist Church, Yadomdo",
    "Revelation Baptist Church, Jayondo",
    "Road of Hope Baptist Church, Kpagnani",
    "Road Side Baptist Church, Kalani",
    "Rock Baptist Church, Banchini",
    "Rock of Ages Baptist Church, Janboni",
    "Second Baptist Church, Roshavel",
    "Round Hill Baptist Church, Tikarini",
    "Sabare Tindang Baptist Church Sabare Tindang",
    "Sakpalebani Baptist Church Sakpalebani",
    "Sakpe Baptist Church, Sakpe",
    "Salinkuka Baptist Church Salinkuka",
    "Santarva Baptist Church, Santarva",
    "Shalom Baptist Church, Chakondonbo",
    "Shelter Baptist Church, Wayido",
    "Shiloh Baptist Church, Gmadado",
    "Shining Baptist Church, Neboni",
    "Skyline Baptist Church, Lungni",
    "St Teliapharo Baptist Church Yapala",
    "St. Magret Baptist Church, Krokoduli",
    "St. Mary Baptist Church, Sakpe",
    "Stand Firm Baptist Church, Kubal Bundido",
    "Sunrise Baptist Church, Nagbaseni",
    "Synagogue Baptist Church, Loloto",
    "Taali Baptist Church",
    "Tabalikpado Baptist Church",
    "Tajudo Baptist Church Tajudo",
    "Talangbal Baptist Church",
    "Talani Baptist Church Talani",
    "Tanbi No2 Holy Grand Baptist Church Tanbi",
    "Tayondo Baptist Church, Tayondo",
    "Tigagamni Baptist Church Tigagamni",
    "Tigmekando Baptist Church Tigmekando",
    "Tinanjerya Baptist Church Tinanjerya",
    "Tree of Life Baptist Church, Nkonta",
    "Tree of Life Baptist Church, Taguldor",
    "Trinity Baptist Church, Nakpamboni",
    "True Love Baptist Church, Bisildo",
    "Truth Baptist Church Kanuldo",
    "Tugbeni Baptist Church, Tugbeni",
    "United Baptist Church, Wasado",
    "Unity Baptist Church, Bonboni",
    "Unity Baptist Church, Pinmen",
    "Unsparing Baptist Church",
    "Victory Baptist Church, Ognodo",
    "Wagambu Baptist Church Wagambu",
    "Waseni Baptist Church, Waseni",
    "Water of Life Baptist Church, Bitim",
    "Weia Baptist Church Weia",
    "Yaakal Baptist Church",
    "Zion Baptist Church, Bulah",
    "Zion Baptist Church, Lesendo",
    "Zion Baptist Church, Omoldo"
  ],
  "Tahima Baptist Association": [
    "Buglan Baptist Church",
    "Dimabi Baptist Church",
    "East Wind Baptist Church",
    "First Baptist Church",
    "Gburimani Baptist Church",
    "Gurugu Baptist Church",
    "Kaa Baptist Church",
    "Kasuyili Baptist Church",
    "Kunguri Baptist Church",
    "Lingbun Baptist Church, Gundaa",
    "Lingun Baptist Church, Yizegu",
    "Munya Baptist Church",
    "Namdu Baptist Church",
    "Nyerizegu Baptist Church",
    "Sankpala Baptist Church",
    "Tolon Baptist Church",
    "Vaggu Baptist Church, Gundaa",
    "Wantugu Baptist Church",
    "Wayamba Baptist Church",
    "Yizegu Baptist Church",
    "Yobzeri Baptist Church",
    "Zali Baptist Church"
  ],
  "Tamale Baptist Association": [
    "Adonai Baptist Church",
    "Bachardor Baptist Church",
    "Bekokolinbe Baptist Church",
    "Bethel Baptist Church",
    "BIWC Baptist Church",
    "Bunlung Baptist Church",
    "Chaayili Baptist Church, Nanton District",
    "Charismatic Baptist Church",
    "Dugushegu Baptist Church",
    "Faith Baptist Church",
    "God's Grace Baptist Church",
    "God's Will Baptist Church",
    "God's Wisdom Baptist Church",
    "Kanville Baptist Church",
    "Koinonia Baptist Church",
    "Koinonia Baptist Church, Tuutengle",
    "Kpene Baptist Church",
    "Kunbudo Baptist Church",
    "Kunbungu Baptist Church, New Town",
    "New Life Community Baptist Church",
    "New Life Community Baptist Church(fuo)",
    "New Life Kanville Tuunaayili Baptist Church",
    "North Gate Community Baptist Church",
    "Pigu Baptist Church",
    "Redemptionbaptist Church",
    "Sachilbo Baptist Church",
    "Sahanaayili Baptist Church",
    "Salvation Baptist Church",
    "Shalom Baptist Church",
    "Togo Baptist Church",
    "Unity Baptist Church",
    "Victory Baptist Church",
    "Vittin Baptist Church, Tamale",
    "Yachado Baptist Church",
    "Yong Baptist Church",
    "Zion Baptist Church"
  ],
  "Wa Baptist Association": [
    "Bakpama Baptist Church",
    "Balazu Baptist Church",
    "Bongberi Baptist Church",
    "Charee Baptist Church",
    "Charlie Baptist Church",
    "Chiangu Baptist Church",
    "Chiatanga Baptist Church",
    "Duong Baptist Church",
    "Gbanko Baptist Church",
    "God's Glory Baptist Church",
    "Guree Baptist Church",
    "Gurimuni Baptist Church",
    "Jirapa Baptist Church",
    "Kagu Baptist Church",
    "Kataa Baptist Church",
    "Konligu Baptist Church",
    "Kpazie Baptist Church",
    "Longu Baptist Church, Saggu",
    "Messiah Baptist Church, Wa",
    "Nyinbale Baptist Church",
    "Papu Baptist Church",
    "Saviour Baptist Church, Sagmatigu",
    "Silaa Baptist Church",
    "Sombo Trinity Baptist Church",
    "St Mathew Baptist Church, Tumu",
    "Tanpieni Baptist Church",
    "Victory Baptist Church, Vieri",
    "Zinnye Community Baptist Church"
  ],
  "Accra North Baptist Association": [
    "Adenta Baptist Church, Adenta",
    "All Nations Baptist Church, Ga Odumasi",
    "All Souls Baptist Church, Afiama",
    "All Souls Baptist Church, Amrahia",
    "All Souls Baptist Church, Oyibi",
    "Ascension Baptist Church, Nsakinaa",
    "Baptist International Worship Centre, Abelenkpe",
    "Baptist International Worship Centre, Kwabenya",
    "Calvary Baptist Church -Adenta",
    "Calvary Baptist Church, Aburi",
    "Calvary Baptist Church, Amasaman Campus",
    "Calvary Baptist Church, Amrahia",
    "Calvary Baptist Church, Kotoku",
    "Calvary Baptist Church, Kpobiman",
    "Calvary Baptist Church, Kpone Katamanso",
    "Calvary Baptist Church, Nsawam",
    "Calvary Baptist Church, Oyibi",
    "Calvary Baptist Church, Shiashie Campus",
    "Charisma Community Baptist Church Ch, Kwafokrom",
    "Charismatic Baptist Church, Asofan",
    "Charismatic Baptist Church, Ayikai Doblo",
    "Charismatic Baptist Church, Okushibiade",
    "Charismatic Baptist Church, Taifa",
    "Christ Baptist Church, Abehenease (Abease)",
    "Christ Baptist Church, Abiriw",
    "Christ Baptist Church, Obosono",
    "Cornerstone Baptist Church, Pillar 2",
    "Ebenezer Baptist Church, Adoagyiri",
    "Ebenezer Baptist Church, Atomic Hills Estate",
    "El- Shaddai Baptist Church, Opah",
    "Emmanuel Baptist Church, Pillar 2",
    "First Baptist Church, Wangara",
    "Good News Baptist Church, Danfa",
    "Good Shepherd Baptist Church, Ayawaso",
    "Gospel Baptist Church, Kodzo Ashong",
    "Grace Baptist Church, Pakro",
    "Grace Baptist Church, Pokuase",
    "Greater Grace Baptist Church, North Taifa",
    "Greater Works Baptist Church, Abokobi Adansi",
    "Greater Works Baptist Church, Achimota",
    "Jubilee Baptist Church, Asofaa",
    "Lakeside Baptist Church -Community 8",
    "Legon Baptist Church",
    "Liberty Baptist Church, Ofankor",
    "Lifeway Baptist Church",
    "Living Seed Baptist Church, Bankyiase",
    "Living Streams Baptist Church, Atomic",
    "Living Water Baptist Church, Ashalaja",
    "Love Community Baptist Church, Abenso",
    "Messiah Baptist Church, Israel",
    "Messiah Baptist Church, Omanjor",
    "Mount Olives Baptist Church Ch- Ashaley Botwe",
    "Mount Olives Baptist Church, Nanakrom",
    "New Covenant Baptist Church, Abelenkpe",
    "New Creation Baptist Church, Nsawam",
    "New Life Baptist Church, Amasaman",
    "Overcomers Baptist Church, Asofaa",
    "Peace Community Baptist Church",
    "Power of Praise Baptist Church, Egakope",
    "Prince of Peace Baptist Church, Nii Boi Town",
    "Providence Baptist Church, Kisseiman",
    "Redeemed Baptist Church Ch -Kpone Bawaleshie",
    "Redeemed Baptist Church, Boi-akporman",
    "Redeemed Baptist Church, Danfa",
    "Redeemed Baptist Church, Madina Estate-ogbojo",
    "Rehoboth Baptist Church",
    "Restoration Baptist Church, Alajo",
    "Revival Baptist Church, Sakyikrom",
    "Shalom Baptist Church, Kwesi Nyarko",
    "Spring of Living Water Baptist Church, Musukoo",
    "St. John’s Baptist Church, Ashalaja",
    "St. John’s Baptist Church, Kpobiman",
    "St. John’s Baptist Church, Tantra Hills",
    "Temple of Grace Baptist Church, Agbogba",
    "Temple of Grace Baptist Church, Maaye Hot",
    "Tesano Baptist Church",
    "Tesano Baptist Church, Domeabra",
    "The Shepherd House Baptist Church",
    "Tongues of Fire Baptist Church, Mayera",
    "Trinity Baptist Church, Amamorley, Ga North",
    "Trinity Baptist Church, Kuntunse",
    "Unity Baptist Church, Ayittey Kortor",
    "Unity Baptist Church, Christian Village",
    "Victory Baptist Church- Akramaman",
    "Westmont Baptist Church, Doblo",
    "Winners Baptist Church, Dome – Born Again",
    "Zion Baptist Church, Alhaji"
  ],
  "Accra South Baptist Association": [
    "Abundant Life Baptist Church, Gbegbeyisee",
    "Adoration Baptist Church",
    "All Nations Baptist Church, Sowutuom",
    "All Souls Baptist Church, Afusman",
    "All Souls Baptist Church, Agbogbloshie",
    "All Souls Baptist Church, North Gbawe CP",
    "All Souls Baptist Church, Osu-kinkawe",
    "All South Baptist Church, South la",
    "Amazing Grace Baptist Church, Kasoa",
    "Bethel Baptist Church, Dansoman, Sakaman",
    "Bethel Baptist Church, Galilea Yam Market",
    "Bethel Baptist Church, Odorkor Official Town",
    "Bethel Baptist Church, Weija – Toronto",
    "Bethel Baptist Church, West Gbawe",
    "Calvary Baptist Church – Awoshie",
    "Calvary Baptist Church, Ablekuma",
    "Calvary Baptist Church, Adabraka",
    "Calvary Baptist Church, Akotolante",
    "Calvary Baptist Church, Avornyokope",
    "Calvary Baptist Church, Avornyokope Central",
    "Calvary Baptist Church, Lakeside – Tuba",
    "Calvary Baptist Church, Nungua",
    "Calvary Baptist Church, Opeikuma",
    "Calvary Baptist Church, Teshie",
    "Central Baptist Church, Kasoa",
    "Christ the King Baptist Church, Tipper Junction",
    "Evangel Baptist Church, Amanfrom",
    "Evangel Baptist Church, Mandela",
    "Grace Life Baptist Church, Millennium City",
    "Greater Grace Baptist Church, Kasoa- Kojo Oku",
    "Hope Baptist Church, Chantan",
    "Jubilee Life Baptist Church",
    "Liberty Baptist Church, Mataheko",
    "Life Gate Baptist Church, Kasoa New Market",
    "Linyangli Baptist Church, Agbogbloshie",
    "Living Fountain Baptist Church, El Shaddai",
    "Living Fountain Baptist Church, Evangel",
    "Living Waters Baptist Church",
    "Living Waters Baptist Church, Mccarthy Hill",
    "Mamprobi Baptist Church, Mamprobi",
    "Mark Hayford Memorial Baptist Church, Arena",
    "Millennium Calvary Baptist Church Ch. Opeikuma",
    "Nazareth Baptist Church, Santa Maria",
    "New Life Baptist Church, Nyanyano",
    "Shepherd Baptist Church, Maamobi",
    "Temple of Praise Baptist Church, Adogonno",
    "The Living Word Baptist Church, Kokrobitey",
    "Trinity Baptist Church, Kokomlemle",
    "Victory Baptist Church, New Gbawe",
    "Zion Faithlife Baptist Church, Ofaakor"
  ],
  "Dangbe West Baptist Association": [
    "Asutsuare Eatly Church Baptist Church",
    "Berea Baptist Church, Kadjanya",
    "Bethany Baptist Church, Senchi",
    "Bethel Baptist Church, Atua",
    "Bethlehem Baptist Church, Asuom Adjikpo",
    "Central Baptist Church, Shai-hills",
    "Dromi Baptist Church",
    "First Baptist Church Akosombo",
    "First Baptist Church Juapong",
    "Glorious Baptist Church Frankadua",
    "Glorious Baptist Church, Somanya",
    "Grace Baptist Church, Odumase",
    "Grace Baptist Church, Oterkporlu",
    "Hope Baptist Church, Adjena",
    "Landmark Baptist Church, Doryumu",
    "Liberty Baptist Church, Afedeh",
    "Life Baptist Church",
    "Living Water Baptist Church, Okwenya",
    "Love Community Baptist Church, Somanya",
    "Mampong All Love Church Baptist Church",
    "Messiah Baptist Church, Otrokpe",
    "New Life Baptist Church, Somanya",
    "Nyanyuie Baptist Church, Old Akrade",
    "Redeemed Baptist Church, Gyakiti",
    "Showers Baptist Church, Odumase",
    "Stump Baptist Church, Adela-kope",
    "Trinity Baptist Church, Asesewa",
    "Unity Baptist Church, Mpakadan",
    "Victory Baptist Church S-line",
    "Victory Comm Baptist Church, Dodowa",
    "Winners Baptist Church, Kpong"
  ],
  "Dangme East Baptist Association": [
    "Amazing Grace Baptist Church, Ahwiam",
    "Bethel Baptist Church, Lekpongunor",
    "Dlomi Baptist Church, English - Kenya",
    "Evangelical Baptist Church, Prampram",
    "First Baptist Church, Mepe",
    "Glory Baptist Church, Kasseh",
    "Good News Baptist Church, Gbagbavuenu",
    "Grace Baptist Church, Aveyime",
    "Grace Baptist Church, Battor",
    "Harvest Time Baptist Church, Sege",
    "Hope Baptist Church, Akplabanya",
    "Living Faith Baptist Church, Old Ningo",
    "Mercy Baptist Church, New Ningo",
    "Miracle Baptist Church, Ada - Foah",
    "Miracle Baptist Church, Anyamam",
    "Mount Olivet Baptist Church, Aveyime",
    "New Life Baptist Church, Aglobakpo",
    "Patmos Baptist Church, Azzizakpe",
    "Peace Baptist Church-dawhenya",
    "Redeemer Baptist Church, Goi",
    "Revival Baptist Church, Ayetepa",
    "Showers Baptist Church, Tsopoli",
    "Solid Rock Baptist Church, Wokumagheh",
    "St. John Baptist Church, Kunyenya",
    "Triumphant Baptist Church, Afienya",
    "Victory Baptist Church, Tamatoku"
  ],
  "Eastern Baptist Association": [
    "Adom Asempa Baptist Church, Akim Subi",
    "Agya Yaw Baptist Church",
    "Ascension Baptist Church, Akim Abodom",
    "Bethel Baptist Church, Kade",
    "Bethel Baptist Church, Koforidua",
    "Calvary Baptist Church, Asuom",
    "Calvary Baptist Church, Osino",
    "Christ Baptist Church, Suhum",
    "Ebenezer Baptist Church, Akwatia",
    "Emmanuel Baptist Church, Adankrono",
    "Evangel Baptist Church, Akim Oda",
    "First Baptist Church, Akim Manso",
    "Grace & Truth Baptist Church, Akim Asuboa",
    "Grace Baptist Church, Akim Tafo",
    "Harvest Baptist Church, Suhum",
    "Jubilee Baptist Church, Bunso",
    "Jubilee Baptist Church, Moseaso",
    "Living Word Baptist Church, Akim Bosuso",
    "Location of Church Baptist Church",
    "Macedonia Baptist Church, Akim Swedru",
    "Messiah Baptist Church, Akim Swedru",
    "New Creation Baptist Church, Koforidua",
    "New Hope Baptist Church, Boadua",
    "Nkunim Baptist Church, Kade",
    "Peace Baptist Church, Akim Begoro",
    "Redemption Baptist Church, Akim Oda",
    "Repentance Baptist Church, Akim Pramkese",
    "Resurrection Baptist Church, Kade",
    "Revelation Baptist Church, Anomakojo",
    "Rock Baptist Church, Suhum",
    "Shalom Baptist Church, Kyebi",
    "Solid Rock Baptist Church, Osenase",
    "Trinity Baptist Church, Akorabo",
    "Unity Baptist Church, Akim Oda",
    "Upper Room Baptist Church, Achiase",
    "Victory Baptist Church, Asamankese",
    "Victory Baptist Church, Nkwantanang",
    "Vision Baptist Church, Adeiso"
  ],
  "North Volta Baptist Association": [
    "Asumdwe Baptist Church, Nkunya Wongong",
    "Belivers Baptist Church, Branease",
    "Calvary Baptist Church, Area 52, Ho",
    "Calvary Baptist Church, Central, Ho",
    "Calvary Baptist Church, Fiave Ho",
    "Calvary Baptist Church, Lokoe, Ho",
    "Charismatic Baptist Church, Kpando",
    "Divine Baptist Church, Ahamanso",
    "Emmanuel Baptist Church, Sibi",
    "First Baptist Church, Dodo-amanfrom",
    "Grace Baptist Church - Hohoe",
    "Grace Baptist Church, Agou",
    "Grace Baptist Church, Damanko",
    "Graceland Baptist Church, Hohoe",
    "Hope Baptist Church - Kpassa",
    "Hour of Grace Baptist Church, Jasikan",
    "Joy Baptist Church, Kpassa",
    "Jyasayor Baptist Church, Krachi",
    "Living Baptist Church, Obiteye",
    "Living Word Baptist Church, Tinase",
    "Miracle Baptist Church, Ntumda",
    "Mt. Zion Baptist Church, Tribu",
    "Nabul Baptist Church, Togo Boarder",
    "New Life Baptist Church, Bonatse",
    "Nyame Adom Baptist Church, Hohoe",
    "Redemption Baptist Church - Kledzo (Hohoe)",
    "Redemption Baptist Church, Worawora",
    "Restoration Baptist Church, N-asakyri",
    "Revival Baptist Church - Nabu",
    "Rhema Baptist Church, Kejebi",
    "Salvation Baptist Church, Jumbo",
    "Salvation Baptist Church, Nkwanta",
    "Shalom Baptist Church, Ampayo",
    "Trinity Baptist Church - Lolobi Kumasi",
    "Triumphant Baptist Church, Dambai",
    "Victory Baptist Church, Agou",
    "Victory Baptist Church, Ketekrachi",
    "Zion Baptist Church, Kpassa"
  ],
  "South Volta Baptist Association": [
    "Abundant Baptist Church, Akatsi",
    "Action Baptist Church, Glidzi-agbo",
    "Amen Baptist Church, Atitekpo",
    "Ascension Baptist Church, Mafi Dadodoe",
    "Bethany Baptist Church, Kpohega",
    "Bethel Baptist Church, Glapedo - Aflao",
    "Calvary Hill Baptist Church, Kpekpo",
    "Denver Baptist Church, Sogakope",
    "Destiny Baptist Church, Yorkitikpo",
    "Dominion Baptist Church, Dabala",
    "Ebenezer Baptist Church, Tenyokope - Aflao",
    "Faith Baptist Church, Mafi Agbekpame",
    "Faith Baptist Church, Mafi Yiangor",
    "Faith Baptist Church, Yorve",
    "Faith Baptist Church, Ziope",
    "First Baptist Church, Agorkpanu - Aflao",
    "Foundation Baptists Church, Agbozume",
    "Garden Baptist Church, Ehi",
    "Garden Baptist Church, Mafi Kumasi",
    "Gethsemane Baptist Church, Anyanui",
    "Godsway Baptist Church, Mafi Mawuekpor",
    "Grace Baptist Church, Avegorme",
    "Grace Baptist Church, Mafi Adiekpe",
    "Hebrone Baptist Church, Mafi Wudzrolo",
    "Holy Spirit Baptist Church, Tosukpo",
    "Hope Baptist Church, Mafi Wute",
    "Jubilee Baptist Church, Anloga",
    "Kingdom Baptist Church, Blekusu",
    "Liberty Baptist Church, Mafi Twala",
    "Living Water Baptist Church, Ahiagbakope",
    "Love Baptist Church, Mafi Meyikpor",
    "Maranatha Baptist Church, Mafi Adidome",
    "New Jerusalem Baptist Church, Mafi Kpedzegbe",
    "New Life Baptist Church, Mafi Kpokope",
    "Overcomers Baptist Church, Glidzi - Agbo",
    "Praise Baptist Church, Keta",
    "Redemption Baptist Church, 2nd Lowcost, Aflao",
    "Rock of Ages Baptist Church, Dzodze",
    "Salvation Baptist Church, Hleve",
    "Salvation Baptist Church, Mafi Gborkope",
    "Shalom Baptist Church, Aflao Beat 9",
    "Shiloh Baptist Church, Penyi",
    "Unity Baptist Church, Mafi Anfoe",
    "Victory Baptist Church, Adina",
    "Victory Baptist Church, Mafi Bekpo",
    "Vision Baptist Church, Mafi Ameworlorkope",
    "Word Baptist Church, Denu"
  ],
  "Tema Central Baptist Association": [
    "Abundant Grace Baptist Church, C20",
    "Agape Baptist Church, New Ablekuman",
    "Bread of Life Baptist Church, Peaceland",
    "Calvary Baptist Church, Lashibi-C17",
    "Christ Baptist Church, C1",
    "Christ Temple Baptist Church, C22",
    "Covenant Baptist Church, Beachroad-tema Newtown",
    "Dominion Baptist Church, Newland",
    "Dromi Baptist Church",
    "El-shaddai Baptist Church, Kanewu",
    "Elshaddai Baptist Church, Zion City",
    "Emmanuel Baptist Church, Kpone",
    "Faithway Baptist Church, Bankuman-tema Newtown",
    "First Baptist Church Jericho-ashaiman",
    "First Baptist Church, C5",
    "Gateway Baptist Church, C11",
    "Goodnews Baptist Church, Cambodia",
    "Goodnews Baptist Church, Zenu",
    "Goodshepherd Baptist Church, Samco",
    "Grace Baptist Church, Sakumono",
    "Grace Community Baptist Church, East Airport",
    "Greater Love Baptist Church, P.s. Global",
    "Hope Baptist Church, Meridian Junction-Tema Newtown",
    "Liberty Baptist Church, C25",
    "Life Baptist Church",
    "Living Bread Baptist Church, Kpone-Haana",
    "Livingwaters Baptist Church, Saki",
    "Livingword Baptist Church, Gbetsile",
    "Love Baptist Church, C2",
    "Mercy Baptist Church, Kubekrom",
    "Mt. Olivet Baptist Church, C9",
    "Mt. Zion Baptist Church, Mid-east",
    "Newlife Baptist Church, Bethlehem",
    "Redemption Baptist Church, Nungua",
    "Ressurrection Baptist Church, K1",
    "Salvation Baptist Church, Ashiaman-Tema Newtown",
    "Shalom Baptist Church, Dawhenya",
    "Triumphant Grace Baptist Church, Afienya",
    "Triumphant Grace Baptist Church, C17",
    "Victory Baptist Church, Spintext"
  ],
  "Cape Coast Baptist Association": [
    "Abundant Grace Baptist Church Akotokyir",
    "Adom Baptist Church Anomabo",
    "Adom Baptist Church Ola-cape Coast",
    "Amazing Grace Baptist Church, Assin Breku",
    "Amazing Love Baptist Church Ucc-kwaprow",
    "Berea Baptist Church Abakrampa",
    "Calvary Road Baptist Church Mankesm",
    "Emmanuel Baptist Church, Elmina",
    "First Baptist Church Twifo Praso",
    "Grace Baptist Church-twifo Hemang",
    "Living Word Baptist Church - Twifo Praso",
    "New Creation Baptist Church - Assin Fosu",
    "New Life Baptist Church - Apewosika",
    "Praise Baptist Church - Kakumdo",
    "Redemption Baptist Church - Cape Coast",
    "Redemption Baptist Church - Katakyiase",
    "Redemption Baptist Church -Assin Fosu",
    "Redemption Baptist Church-amoabeng",
    "Redemption Baptist Church-dominase",
    "Redemption Baptist Church-komenda",
    "Redemption Baptist Church-saltpond",
    "Trinity Baptist Church Effutu",
    "Vine Yard Baptist Church Abura-dunkwa"
  ],
  "Hope Baptist Association": [
    "Ascension Baptist Church, Badowa",
    "Central Baptist Church – Enchie",
    "Ebenezer Baptist Church, Abesewa Gyamang",
    "Ebenezer Baptist Church, Den. Fosu",
    "Emmanuel Baptist Church, Petapon",
    "Evangelical Baptist Church Kpk",
    "First Baptist Church Adjeikwame",
    "First Baptist Church Akyempim",
    "First Baptist Church Denkyira Asikuma",
    "First Baptist Church Meradan",
    "First Baptist Church, Babianiha",
    "First Baptist Church, Buabenso",
    "First Baptist Church, Buabin",
    "First Baptist Church, Dunkwa",
    "Glorious Baptist Church, Prestea",
    "Grace Baptist Church Wasa Ntwietwena",
    "Holy Baptist Church, Heman",
    "Jesus Is the Light Baptist Church Abreshia",
    "Liberty Baptist Church, Ayanfuri",
    "Macedonia Baptist Church Denkyira Asma Camp",
    "Mont Zion Baptist Church",
    "Peace and Love Baptist Church Nanankoh",
    "Peace Baptist Church Nkonya",
    "Restoration Baptist Church Bowdie",
    "Resurrection Baptist Church Denkyira Amoafo",
    "Revival Baptist Church, Bogoso",
    "Salvation Baptist Church, Asankragua",
    "Solid Rock Baptist Church Kyekyiewere",
    "Trinity Baptist Church, Gyamang",
    "Victory Baptist Church Akropong"
  ],
  "Nzema Baptist Association": [
    "Aiyinasi First Baptist Church",
    "Asanta Baptist Church-asanta",
    "Basake Baptist Church-basake",
    "Believers Baptist Church-mbim",
    "Bethel Batist-jaway Wharf Baptist Church",
    "Bible Baptist Church-nyamebekyere",
    "Calvary Baptist Church-esiama",
    "Christ Within Baptist Church, Axim",
    "Compassion Without Borders Baptist Church",
    "Ekpu Baptist Church-ekpu",
    "Faith Baptist Church-kikam",
    "Glorious Baptist Church-axim",
    "Glorious Baptist Church-half Assini",
    "Good Shepherd Baptist Church-bonyere",
    "Lamb of God Baptist Church-azulet",
    "Life in Christ Baptist Church-adusuazo",
    "Mangyea Baptist Church-mangyea",
    "Redeemer Baptist Church-atwebanso",
    "Resurrection Baptist Church-bonyere Junction",
    "Salvation Baptist Church-ezinlibo",
    "Tabernacle Baptist Church-nkroful",
    "Temple Baptist Church, Aiyinasi",
    "United Baptist Church-elubo",
    "Victory Baptist Church-tikobo 1"
  ],
  "Sekondi-Takoradi Baptist Association": [
    "Abundant Life Baptist Church, New Site Takoradi",
    "Agape Baptist Church, Awonakrom",
    "All Saint Baptist Church, Tarkwa",
    "Believers Baptist Church, Agege Tarkwa",
    "Believers Baptist Church, Tarkwa",
    "Bible Baptist Church, Race Course",
    "Calvary Baptist Church, Daboase",
    "Emmanuel Baptist Church, Shama",
    "Falls of Glory Baptist Church, Agric Takoradi",
    "First Baptist Church, Aboso",
    "First Baptist Church, Agona Wassa",
    "First Baptist Church, Sekondi",
    "First Baptist Church, Takoradi",
    "Full Gospel Baptist Church, Kojokrom",
    "God’s Power Baptist Church, Takwa",
    "Good News Baptist Church, New Atoabo",
    "Good Shepherd Baptist Church, Dompim",
    "Harvest Field Baptist Church, Aboadze",
    "Holy Baptist Church, Tamso, Tarkwa",
    "Joy Baptist Church, Mpohor",
    "Light Baptist Church, Huni-valley",
    "Messiah Baptist Church Anomakrom (Tarkwa)",
    "New Life Baptist Church, Agona Nkwanta",
    "Open Door Baptist Church, Anaji",
    "Resurrection Baptist Church, Effiakuma",
    "Resurrection Baptist Church, Mampong",
    "Sekondi-takoradi Baptist Church",
    "Solid Rock Baptist Church, Kwesimintsim",
    "Source of Life Baptist Church, Apowa",
    "St. Joseph Baptist Church, Anaji",
    "Thirsty Souls Baptist Church, Takoradi",
    "Trinity Baptist Church, Akyempim",
    "Triumphant Baptist Church, Assorko",
    "Vision Baptist Church, Mile 10 Tarkwa"
  ],
  "Swedru Baptist Association": [
    "Bethel Baptist Church",
    "Blessing Baptist Church",
    "Calvary Baptist Church",
    "Christ the King Baptist Church",
    "Ebeneezer Baptist Church",
    "Emmanuel Baptist Church",
    "First Baptist Church",
    "Frontier Baptist Church",
    "Gate Way Baptist Church",
    "Goodnews Baptist Church",
    "Grace Baptist Church Ajumako",
    "Grace Baptist Church Asikuma",
    "Greater Glory Baptist Church",
    "Harvester Baptist Church",
    "Hope Baptist Church",
    "Lampstand Baptist Church",
    "Liberty Baptist Church",
    "Living Fountain Baptist Church",
    "Living Word Baptist Church",
    "Maranatha Baptist Church",
    "New Life Baptist Church",
    "Promise Baptist Church Bobikuma",
    "Redeem Baptist Church",
    "Restoration Baptist Church",
    "Resurrection Baptist Church",
    "Resurrection Baptist Church Bobikuma",
    "Rock of Ages Baptist Church",
    "St Stephen Baptist Church, Gomoa Denkyira",
    "Trinity Baptist Church",
    "Upper Room Baptist Church",
    "Victory Baptist Church"
  ],
  "Winneba Baptist Association": [
    "Alpha and Omega Baptist Church, Winneba",
    "Amanful Baptist Church, Amanful",
    "Apam Baptist Church, Gomoa Apam",
    "Aseibu/pomadze Baptist Church, Gomoa Pomadze",
    "Asomdwee Baptist Church, Nsuekyir",
    "Awomberew Baptist Church, Awomberew",
    "Believers Baptist Church, Gomoa Akoti",
    "Dago Baptist Church, Gomoa Dago",
    "Fawommany Baptist Church, Gomoa Fawommany",
    "Fetteh Baptist Church",
    "Freedom Baptist Church, Awutu Beraku",
    "Goodhope Baptist Church, Effutu Gyangyanadze",
    "Grace Baptist Church, Ahwir Nkwanta",
    "Hwida Baptist Church, Gomoa Hwida",
    "Kweikrom Baptist Church, Gomoa Kweikrom",
    "Mankoadze Baptist Church, Gomoa Mankoadze",
    "New Life Baptist Church, Gomoa Ojobi",
    "Northgate Baptist Church, Winneba",
    "Obiri Baptist Church, Gomoa Obiri",
    "Peace Baptist Church, Worabeba",
    "Refuge Baptist Church, Gomoa Buduburam",
    "Sankor Baptist Church, Sankor",
    "Saviour Baptist Church, Senya",
    "Senya Baptist Church, Senya Beraku",
    "Simpa Baptist Church, Winneba"
  ]
};

export const SECTORS = Object.keys(SECTOR_ASSOCIATION_MAP);

// All associations (flat list, for backward compatibility / reports)
export const ASSOCIATIONS = Object.values(SECTOR_ASSOCIATION_MAP).flat();

// Fellowship exports retained for backward compatibility with older admissions screens.
export const FELLOWSHIPS = ["Fellowship 1", "Fellowship 2", "Fellowship 3", "Fellowship 4"];

export const ASSOCIATION_FELLOWSHIP_MAP: Record<string, string[]> = Object.fromEntries(
  ASSOCIATIONS.map((association) => [association, FELLOWSHIPS])
);

export function getFellowshipsForAssociation(association: string): string[] {
  return ASSOCIATION_FELLOWSHIP_MAP[association] || [];
}

export function getChurchesForAssociation(association: string): string[] {
  return ASSOCIATION_CHURCH_MAP[association] || [];
}

export const ZONES = [
  "Zone 1",
  "Zone 2",
  "Zone 3",
  "Zone 4",
  "Zone 5",
];

export function getAssociationsForSector(sector: string): string[] {
  return SECTOR_ASSOCIATION_MAP[sector] || [];
}

export function getSectorForAssociation(association: string): string | undefined {
  return SECTORS.find((sector) => SECTOR_ASSOCIATION_MAP[sector].includes(association));
}

export const MARITAL_STATUSES = [
  { value: "single", label: "Single" },
  { value: "married", label: "Married" },
  { value: "widowed", label: "Widowed" },
  { value: "divorced", label: "Divorced" },
];

export const MARRIAGE_TYPES = [
  { value: "ordinance", label: "Ordinance" },
  { value: "customary", label: "Customary" },
];

export const TITLE_OPTIONS = [
  "Rev",
  "Rev Dr.",
  "Rev Mrs.",
  "Mr.",
  "Mrs.",
  "Miss",
  "Pastor",
];

export const MINISTER_STATUSES = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "retired", label: "Retired" },
];
